name: Create orphaned signature

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  create_signature:
    name: create container and signature
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set tag
        id: set-tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TAG="test-$SHORT_SHA"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/jtaeuber/prune-orphaned-cosign-sig
          tags: |
            latest
            ${{ env.TAG }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: build-push
        with:
          context: .
          platforms: linux/amd64
          provenance: false
          sbom: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Sign Push
        run: |
          cosign sign --key env://COSIGN_KEY --tlog-upload=false ghcr.io/jtaeuber/prune-orphaned-cosign-sig@${{ steps.build-push.outputs.digest }}
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}

  delete_container:
    name: delete container
    runs-on: ubuntu-latest
    needs: create_signature
    steps:
      - name: Remove container
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: prune-orphaned-cosign-sig
          prune-untagged: true
          prune-tags-regexes: |
            ^test-

  test-action:
    needs: delete_container
    uses: ./.github/workflows/test-action.yaml
    secrets: inherit
