name: Test Action

on:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  test_action_dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Action dryrun
        uses: ./
        with:
          package_name: prune-orphaned-cosign-sig
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          dryrun: true

  # test_action:
  #   runs-on: ubuntu-latest
  #   needs: test_action_dryrun
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Run Action
  #       uses: ./
  #       with:
  #         package_name: prune-orphaned-cosign-sig
  #         gh_token: ${{ secrets.GITHUB_TOKEN }}
